import 'dart:math';

/// Quotes keyed by language code so more languages can be added without touching callers.
/// "zh" is Simplified Chinese; "zh-Hant" is Traditional. "pt" is Brazilian Portuguese.
class MotivationQuotes {
  static const Map<String, List<String>> byLanguage = {
    'en': [
      "Start now. Perfect comes later.",
      "One small step today beats a big plan tomorrow.",
      "Deadlines are friends, not enemies.",
      "Don't wait for motivation. Build discipline.",
      "Small progress is still progress.",
      "Focus. Work. Finish.",
      "You run today. Not laziness.",
      "Tired is okay. Quitting is not.",
      "What you delay today becomes tomorrow's weight.",
      "Do it now. Relax later.",
      "You are stronger than your excuses.",
      "Done beats perfect.",
      "Check off one thing today.",
      "Consistency beats motivation.",
      "Big goals start with small tasks.",
      "Don't compare your start to someone's finish.",
      "Time keeps moving. Move with it.",
      "Work hard today, be proud tomorrow.",
      "Break big problems into small steps.",
      "Failure is data, not the end.",
      "Begin now, not later.",
      "One focused hour beats a lazy day.",
      "You've survived harder days.",
      "Discipline is self-respect.",
      "Don't let the deadline chase you.",
      "Finish one thing and feel the relief.",
      "A plan without action is just a wish.",
      "Slow is fine, as long as it's finished.",
      "Today is yours. Use it well.",
      "Project done, mind at ease.",
    ],
    'id': [
      "Mulai sekarang. Sempurna menyusul.",
      "Satu langkah kecil hari ini lebih baik dari rencana besar besok.",
      "Deadline itu teman, bukan musuh.",
      "Jangan tunggu semangat. Bangun disiplin.",
      "Kemajuan kecil tetap kemajuan.",
      "Fokus. Kerjakan. Selesaikan.",
      "Kamu yang mengendalikan hari ini, bukan rasa malas.",
      "Capek boleh, menyerah jangan.",
      "Yang kamu tunda hari ini jadi beban besok.",
      "Kerjakan sekarang, santai kemudian.",
      "Kamu lebih kuat dari alasanmu.",
      "Selesai lebih baik daripada sempurna.",
      "Centang satu hal hari ini.",
      "Konsisten mengalahkan motivasi.",
      "Target besar dimulai dari tugas kecil.",
      "Jangan bandingkan awalmu dengan akhir orang lain.",
      "Waktu terus berjalan. Ikutlah bergerak.",
      "Kerja keras hari ini, bangga besok.",
      "Pecah masalah besar jadi langkah kecil.",
      "Gagal itu data, bukan akhir.",
      "Mulai sekarang, bukan nanti.",
      "Satu jam fokus mengalahkan sehari bermalas-malasan.",
      "Kamu sudah melewati hari yang lebih berat.",
      "Disiplin adalah bentuk menghargai diri sendiri.",
      "Jangan biarkan deadline mengejarmu.",
      "Selesaikan satu hal, rasakan leganya.",
      "Rencana tanpa aksi cuma angan-angan.",
      "Pelan tak apa, asal selesai.",
      "Hari ini milikmu. Pakai dengan baik.",
      "Proyek selesai, hati tenang.",
    ],
    'zh': [
      "现在就开始，完美留给以后。",
      "今天迈出一小步，胜过明天的宏大计划。",
      "截止日期是朋友，不是敌人。",
      "别等有动力才行动，先养成自律。",
      "小小的进步也是进步。",
      "专注，行动，完成。",
      "今天由你做主，而不是懒惰。",
      "累了可以休息，但不要放弃。",
      "今天拖延的事，明天会变成负担。",
      "现在就做，之后才能安心休息。",
      "你比自己的借口更强大。",
      "完成比完美更重要。",
      "今天先划掉一件事。",
      "坚持比动力更可靠。",
      "大目标从小任务开始。",
      "别拿自己的起点去比别人的终点。",
      "时间不会停，你也别停。",
      "今天努力，明天自豪。",
      "把大问题拆成小步骤。",
      "失败只是数据，不是终点。",
      "从现在开始，别等以后。",
      "专注的一小时，胜过懒散的一整天。",
      "你已经熬过比这更难的日子。",
      "自律是对自己的尊重。",
      "别让截止日期追着你跑。",
      "做完一件事，感受那份轻松。",
      "没有行动的计划只是愿望。",
      "慢一点没关系，做完就好。",
      "今天属于你，好好利用。",
      "项目完成，心里踏实。",
    ],
    'zh-Hant': [
      "現在就開始，完美留給之後。",
      "今天邁出一小步，勝過明天的宏大計畫。",
      "截止日期是朋友，不是敵人。",
      "別等有動力才行動，先養成自律。",
      "小小的進步也是進步。",
      "專注，行動，完成。",
      "今天由你做主，而不是懶惰。",
      "累了可以休息，但不要放棄。",
      "今天拖延的事，明天會變成負擔。",
      "現在就做，之後才能安心休息。",
      "你比自己的藉口更強大。",
      "完成比完美更重要。",
      "今天先劃掉一件事。",
      "堅持比動力更可靠。",
      "大目標從小任務開始。",
      "別拿自己的起點去比別人的終點。",
      "時間不會停，你也別停。",
      "今天努力，明天自豪。",
      "把大問題拆成小步驟。",
      "失敗只是資料，不是終點。",
      "從現在開始，別等以後。",
      "專注的一小時，勝過懶散的一整天。",
      "你已經熬過比這更難的日子。",
      "自律是對自己的尊重。",
      "別讓截止日期追著你跑。",
      "做完一件事，感受那份輕鬆。",
      "沒有行動的計畫只是願望。",
      "慢一點沒關係，做完就好。",
      "今天屬於你，好好利用。",
      "專案完成，心裡踏實。",
    ],
    'ja': [
      "まず始めよう。完璧はあとから。",
      "今日の小さな一歩は、明日の大きな計画に勝る。",
      "期限は敵じゃない、味方だ。",
      "やる気を待たず、習慣を作ろう。",
      "小さな前進も前進。",
      "集中。実行。完了。",
      "今日を動かすのは、怠け心じゃなくあなた。",
      "疲れてもいい。でもやめない。",
      "今日先延ばしにしたことは、明日の重荷になる。",
      "今やれば、あとで安心できる。",
      "あなたは言い訳より強い。",
      "完璧より完了。",
      "今日はひとつ、やり終えよう。",
      "やる気より継続。",
      "大きな目標も、小さなタスクから。",
      "自分のスタートを、人のゴールと比べない。",
      "時間は止まらない。一緒に進もう。",
      "今日がんばれば、明日誇れる。",
      "大きな問題は小さな一歩に分けよう。",
      "失敗はデータ。終わりじゃない。",
      "始めるなら今。",
      "集中した1時間は、だらけた1日に勝つ。",
      "もっとつらい日も乗り越えてきた。",
      "自己管理は自分への思いやり。",
      "期限に追われる前に動こう。",
      "ひとつ終わらせて、ほっとしよう。",
      "行動のない計画はただの願い。",
      "ゆっくりでも、終わらせればいい。",
      "今日はあなたのもの。大切に使おう。",
      "プロジェクト完了、心も軽く。",
    ],
    'ko': [
      "지금 시작하세요. 완벽은 나중에.",
      "오늘의 작은 한 걸음이 내일의 큰 계획보다 낫습니다.",
      "마감은 적이 아니라 친구입니다.",
      "의욕을 기다리지 말고 습관을 만드세요.",
      "작은 진전도 진전입니다.",
      "집중하고, 실행하고, 끝내세요.",
      "오늘의 주인은 게으름이 아니라 당신입니다.",
      "지쳐도 괜찮아요. 포기만 하지 마세요.",
      "오늘 미룬 일은 내일의 짐이 됩니다.",
      "지금 하고, 나중에 편히 쉬세요.",
      "당신은 핑계보다 강합니다.",
      "완벽보다 완료가 낫습니다.",
      "오늘 한 가지만 체크하세요.",
      "꾸준함이 의욕을 이깁니다.",
      "큰 목표도 작은 일부터 시작됩니다.",
      "내 출발점을 남의 결승선과 비교하지 마세요.",
      "시간은 계속 흐릅니다. 함께 움직여요.",
      "오늘 열심히 하면 내일 뿌듯합니다.",
      "큰 문제는 작은 단계로 나누세요.",
      "실패는 데이터일 뿐, 끝이 아닙니다.",
      "나중 말고 지금 시작하세요.",
      "집중한 한 시간이 게으른 하루보다 낫습니다.",
      "더 힘든 날도 이겨냈잖아요.",
      "자기관리는 나를 존중하는 일입니다.",
      "마감에 쫓기지 마세요.",
      "하나를 끝내고 후련함을 느껴보세요.",
      "행동 없는 계획은 바람일 뿐입니다.",
      "느려도 괜찮아요. 끝내기만 하면 됩니다.",
      "오늘은 당신의 것입니다. 잘 쓰세요.",
      "프로젝트 완료, 마음도 편안.",
    ],
    'es': [
      "Empieza ya. Lo perfecto llega después.",
      "Un pequeño paso hoy vale más que un gran plan mañana.",
      "Las fechas límite son aliadas, no enemigas.",
      "No esperes motivación. Construye disciplina.",
      "Un pequeño avance sigue siendo avance.",
      "Concéntrate. Trabaja. Termina.",
      "Hoy mandas tú, no la pereza.",
      "Cansarse está bien. Rendirse, no.",
      "Lo que aplazas hoy pesa más mañana.",
      "Hazlo ahora. Descansa después.",
      "Eres más fuerte que tus excusas.",
      "Hecho es mejor que perfecto.",
      "Tacha una cosa hoy.",
      "La constancia vence a la motivación.",
      "Las grandes metas empiezan con tareas pequeñas.",
      "No compares tu inicio con la meta de otro.",
      "El tiempo no se detiene. Muévete con él.",
      "Esfuérzate hoy, sentirás orgullo mañana.",
      "Divide los grandes problemas en pasos pequeños.",
      "Fracasar es información, no el final.",
      "Empieza ahora, no luego.",
      "Una hora de enfoque vale más que un día perdido.",
      "Ya has superado días más duros.",
      "La disciplina es respeto por ti mismo.",
      "No dejes que la fecha límite te persiga.",
      "Termina una cosa y siente el alivio.",
      "Un plan sin acción es solo un deseo.",
      "Ir despacio está bien, si lo terminas.",
      "Hoy es tuyo. Aprovéchalo.",
      "Proyecto terminado, mente tranquila.",
    ],
    'pt': [
      "Comece agora. O perfeito vem depois.",
      "Um pequeno passo hoje vale mais que um grande plano amanhã.",
      "Prazos são aliados, não inimigos.",
      "Não espere motivação. Construa disciplina.",
      "Pequeno progresso ainda é progresso.",
      "Foco. Trabalho. Conclusão.",
      "Hoje quem manda é você, não a preguiça.",
      "Cansar tudo bem. Desistir, não.",
      "O que você adia hoje vira peso amanhã.",
      "Faça agora. Descanse depois.",
      "Você é mais forte que suas desculpas.",
      "Feito é melhor que perfeito.",
      "Risque uma tarefa hoje.",
      "Constância vence motivação.",
      "Grandes metas começam com tarefas pequenas.",
      "Não compare seu começo com o fim de outra pessoa.",
      "O tempo não para. Acompanhe.",
      "Dedique-se hoje, orgulhe-se amanhã.",
      "Divida grandes problemas em passos pequenos.",
      "Falhar é dado, não é o fim.",
      "Comece agora, não depois.",
      "Uma hora de foco vale mais que um dia de preguiça.",
      "Você já superou dias mais difíceis.",
      "Disciplina é respeito por si mesmo.",
      "Não deixe o prazo correr atrás de você.",
      "Termine uma coisa e sinta o alívio.",
      "Plano sem ação é só desejo.",
      "Devagar tudo bem, desde que termine.",
      "Hoje é seu. Aproveite bem.",
      "Projeto concluído, mente tranquila.",
    ],
    'de': [
      "Fang jetzt an. Perfekt wird es später.",
      "Ein kleiner Schritt heute schlägt einen großen Plan morgen.",
      "Fristen sind Freunde, keine Feinde.",
      "Warte nicht auf Motivation. Baue Disziplin auf.",
      "Kleine Fortschritte sind trotzdem Fortschritte.",
      "Fokus. Arbeiten. Fertig.",
      "Heute bestimmst du, nicht die Faulheit.",
      "Müde sein ist okay. Aufgeben nicht.",
      "Was du heute aufschiebst, wird morgen zur Last.",
      "Jetzt erledigen. Später entspannen.",
      "Du bist stärker als deine Ausreden.",
      "Erledigt ist besser als perfekt.",
      "Hake heute eine Sache ab.",
      "Beständigkeit schlägt Motivation.",
      "Große Ziele beginnen mit kleinen Aufgaben.",
      "Vergleiche deinen Anfang nicht mit dem Ziel anderer.",
      "Die Zeit läuft weiter. Lauf mit.",
      "Streng dich heute an, sei morgen stolz.",
      "Zerlege große Probleme in kleine Schritte.",
      "Scheitern liefert Daten, kein Ende.",
      "Fang jetzt an, nicht später.",
      "Eine konzentrierte Stunde schlägt einen faulen Tag.",
      "Du hast schon schwerere Tage gemeistert.",
      "Disziplin ist Respekt vor dir selbst.",
      "Lass dich nicht von der Frist jagen.",
      "Schließ eine Sache ab und spür die Erleichterung.",
      "Ein Plan ohne Handlung ist nur ein Wunsch.",
      "Langsam ist okay, solange es fertig wird.",
      "Heute gehört dir. Nutze ihn gut.",
      "Projekt fertig, Kopf frei.",
    ],
    'fr': [
      "Commencez maintenant. Le parfait viendra après.",
      "Un petit pas aujourd’hui vaut mieux qu’un grand plan demain.",
      "Les échéances sont des alliées, pas des ennemies.",
      "N’attendez pas la motivation. Bâtissez la discipline.",
      "Un petit progrès reste un progrès.",
      "Concentration. Travail. Fini.",
      "Aujourd’hui, c’est vous qui décidez, pas la paresse.",
      "Être fatigué, ça va. Abandonner, non.",
      "Ce que vous repoussez aujourd’hui pèse demain.",
      "Faites-le maintenant. Détendez-vous après.",
      "Vous êtes plus fort que vos excuses.",
      "Fait vaut mieux que parfait.",
      "Cochez une chose aujourd’hui.",
      "La régularité bat la motivation.",
      "Les grands objectifs commencent par de petites tâches.",
      "Ne comparez pas votre début à l’arrivée des autres.",
      "Le temps avance. Avancez avec lui.",
      "Donnez tout aujourd’hui, soyez fier demain.",
      "Découpez les gros problèmes en petites étapes.",
      "L’échec est une donnée, pas une fin.",
      "Commencez maintenant, pas plus tard.",
      "Une heure de concentration vaut mieux qu’une journée perdue.",
      "Vous avez déjà survécu à des jours plus durs.",
      "La discipline est une forme de respect de soi.",
      "Ne laissez pas l’échéance vous courir après.",
      "Terminez une chose et savourez le soulagement.",
      "Un plan sans action n’est qu’un souhait.",
      "Lent, ce n’est pas grave, tant que c’est terminé.",
      "Aujourd’hui vous appartient. Profitez-en bien.",
      "Projet terminé, esprit tranquille.",
    ],
    'ar': [
      "ابدأ الآن. الكمال يأتي لاحقًا.",
      "خطوة صغيرة اليوم أفضل من خطة كبيرة غدًا.",
      "المواعيد النهائية أصدقاء لا أعداء.",
      "لا تنتظر الحماس. ابنِ الانضباط.",
      "التقدم الصغير يظل تقدمًا.",
      "ركّز. اعمل. أنجز.",
      "اليوم أنت من يقرر، لا الكسل.",
      "التعب لا بأس به، أما الاستسلام فلا.",
      "ما تؤجله اليوم يصبح عبئًا غدًا.",
      "افعلها الآن، وارتح لاحقًا.",
      "أنت أقوى من أعذارك.",
      "المنجَز خير من المثالي.",
      "أنجز مهمة واحدة اليوم.",
      "الاستمرار يتفوق على الحماس.",
      "الأهداف الكبيرة تبدأ بمهام صغيرة.",
      "لا تقارن بدايتك بنهاية غيرك.",
      "الوقت يمضي، فامضِ معه.",
      "اجتهد اليوم وافخر غدًا.",
      "قسّم المشكلات الكبيرة إلى خطوات صغيرة.",
      "الفشل معلومة، وليس نهاية.",
      "ابدأ الآن، لا لاحقًا.",
      "ساعة من التركيز أفضل من يوم كسول.",
      "لقد تجاوزت أيامًا أصعب من هذا.",
      "الانضباط احترام للذات.",
      "لا تدع الموعد النهائي يطاردك.",
      "أنهِ شيئًا واحدًا واشعر بالارتياح.",
      "خطة بلا عمل مجرد أمنية.",
      "البطء لا بأس به ما دمت ستنهي المهمة.",
      "هذا اليوم لك، فاستثمره جيدًا.",
      "المشروع منجز والبال مرتاح.",
    ],
    'hi': [
      "अभी शुरू करो। परफ़ेक्ट बाद में आएगा।",
      "आज का एक छोटा कदम कल की बड़ी योजना से बेहतर है।",
      "समय-सीमा दोस्त है, दुश्मन नहीं।",
      "प्रेरणा का इंतज़ार मत करो, अनुशासन बनाओ।",
      "छोटी प्रगति भी प्रगति है।",
      "ध्यान लगाओ। काम करो। पूरा करो।",
      "आज तुम तय करो, आलस नहीं।",
      "थकना ठीक है, हार मानना नहीं।",
      "जो आज टालोगे, वही कल बोझ बनेगा।",
      "अभी करो, बाद में आराम करो।",
      "तुम अपने बहानों से ज़्यादा मज़बूत हो।",
      "पूरा किया हुआ काम परफ़ेक्ट से बेहतर है।",
      "आज एक काम पर निशान लगा दो।",
      "निरंतरता प्रेरणा से आगे निकल जाती है।",
      "बड़े लक्ष्य छोटे कामों से शुरू होते हैं।",
      "अपनी शुरुआत की तुलना किसी और की मंज़िल से मत करो।",
      "समय चलता रहता है, तुम भी चलते रहो।",
      "आज मेहनत करो, कल गर्व करो।",
      "बड़ी समस्या को छोटे कदमों में बाँट दो।",
      "असफलता सीख है, अंत नहीं।",
      "अभी शुरू करो, बाद में नहीं।",
      "एक घंटे का ध्यान पूरे दिन के आलस से बेहतर है।",
      "तुमने इससे भी कठिन दिन पार किए हैं।",
      "अनुशासन अपने प्रति सम्मान है।",
      "समय-सीमा को अपना पीछा मत करने दो।",
      "एक काम पूरा करो और राहत महसूस करो।",
      "कर्म के बिना योजना बस एक इच्छा है।",
      "धीरे चलो, बस पूरा करो।",
      "आज का दिन तुम्हारा है, इसे अच्छे से जियो।",
      "परियोजना पूरी, मन शांत।",
    ],
    'th': [
      "เริ่มเลยตอนนี้ ความสมบูรณ์แบบค่อยตามมา",
      "ก้าวเล็ก ๆ วันนี้ ดีกว่าแผนใหญ่ของวันพรุ่งนี้",
      "กำหนดส่งคือเพื่อน ไม่ใช่ศัตรู",
      "อย่ารอแรงบันดาลใจ สร้างวินัยขึ้นมา",
      "ความก้าวหน้าเล็ก ๆ ก็ยังเป็นความก้าวหน้า",
      "โฟกัส ลงมือ ทำให้เสร็จ",
      "วันนี้คุณเป็นคนกำหนด ไม่ใช่ความขี้เกียจ",
      "เหนื่อยได้ แต่อย่าถอดใจ",
      "สิ่งที่เลื่อนวันนี้ จะกลายเป็นภาระของพรุ่งนี้",
      "ทำเลยตอนนี้ แล้วค่อยพักทีหลัง",
      "คุณเข้มแข็งกว่าข้ออ้างของตัวเอง",
      "ทำให้เสร็จดีกว่าทำให้สมบูรณ์แบบ",
      "ติ๊กถูกให้ได้สักอย่างวันนี้",
      "ความสม่ำเสมอชนะแรงบันดาลใจ",
      "เป้าหมายใหญ่เริ่มจากงานเล็ก ๆ",
      "อย่าเอาจุดเริ่มต้นของเรา ไปเทียบกับเส้นชัยของคนอื่น",
      "เวลาเดินต่อไปเสมอ ก้าวไปพร้อมกัน",
      "ตั้งใจวันนี้ ภูมิใจพรุ่งนี้",
      "แบ่งปัญหาใหญ่เป็นก้าวเล็ก ๆ",
      "ความล้มเหลวคือข้อมูล ไม่ใช่จุดจบ",
      "เริ่มตอนนี้ ไม่ใช่ทีหลัง",
      "หนึ่งชั่วโมงที่โฟกัส ดีกว่าทั้งวันที่เอื่อยเฉื่อย",
      "คุณผ่านวันที่หนักกว่านี้มาแล้ว",
      "วินัยคือการให้เกียรติตัวเอง",
      "อย่าปล่อยให้กำหนดส่งไล่ตามคุณ",
      "ทำให้เสร็จสักอย่าง แล้วสัมผัสความโล่งใจ",
      "แผนที่ไม่ลงมือทำ ก็เป็นแค่ความหวัง",
      "ช้าไม่เป็นไร ขอแค่เสร็จ",
      "วันนี้เป็นของคุณ ใช้ให้คุ้มค่า",
      "โปรเจกต์เสร็จ ใจก็สบาย",
    ],
    'vi': [
      "Bắt đầu ngay. Hoàn hảo để sau.",
      "Một bước nhỏ hôm nay hơn một kế hoạch lớn ngày mai.",
      "Hạn chót là bạn, không phải kẻ thù.",
      "Đừng chờ động lực. Hãy xây dựng kỷ luật.",
      "Tiến bộ nhỏ vẫn là tiến bộ.",
      "Tập trung. Làm. Hoàn thành.",
      "Hôm nay bạn làm chủ, không phải sự lười biếng.",
      "Mệt cũng được, bỏ cuộc thì không.",
      "Việc hôm nay trì hoãn sẽ thành gánh nặng ngày mai.",
      "Làm ngay bây giờ. Thư giãn sau.",
      "Bạn mạnh mẽ hơn những lý do của mình.",
      "Xong còn hơn hoàn hảo.",
      "Hôm nay hãy tích xong một việc.",
      "Kiên trì thắng động lực.",
      "Mục tiêu lớn bắt đầu từ việc nhỏ.",
      "Đừng so điểm xuất phát của bạn với đích đến của người khác.",
      "Thời gian cứ trôi. Hãy cùng tiến lên.",
      "Hôm nay cố gắng, ngày mai tự hào.",
      "Chia vấn đề lớn thành các bước nhỏ.",
      "Thất bại là dữ liệu, không phải kết thúc.",
      "Bắt đầu bây giờ, đừng đợi sau.",
      "Một giờ tập trung hơn cả ngày lười biếng.",
      "Bạn đã vượt qua những ngày khó hơn thế.",
      "Kỷ luật là tôn trọng chính mình.",
      "Đừng để hạn chót đuổi theo bạn.",
      "Hoàn thành một việc và cảm nhận sự nhẹ nhõm.",
      "Kế hoạch không hành động chỉ là mong ước.",
      "Chậm cũng được, miễn là xong.",
      "Hôm nay là của bạn. Hãy dùng thật tốt.",
      "Dự án xong, lòng nhẹ nhàng.",
    ],
    'tl': [
      "Magsimula na ngayon. Susunod ang perpekto.",
      "Mas mabuti ang maliit na hakbang ngayon kaysa malaking plano bukas.",
      "Kaibigan ang deadline, hindi kaaway.",
      "Huwag hintayin ang motibasyon. Buuin ang disiplina.",
      "Progreso pa rin ang maliit na progreso.",
      "Pokus. Gawin. Tapusin.",
      "Ikaw ang masusunod ngayon, hindi ang katamaran.",
      "Okay lang mapagod. Huwag lang sumuko.",
      "Ang ipinagpaliban mo ngayon ay bigat bukas.",
      "Gawin na ngayon. Magpahinga mamaya.",
      "Mas malakas ka kaysa sa mga dahilan mo.",
      "Mas mabuti ang tapos kaysa perpekto.",
      "Mag-check ng isang bagay ngayon.",
      "Mas panalo ang consistency kaysa motibasyon.",
      "Nagsisimula sa maliliit na gawain ang malalaking layunin.",
      "Huwag ihambing ang simula mo sa finish line ng iba.",
      "Tuloy-tuloy ang oras. Sumabay ka.",
      "Magsikap ngayon, magmalaki bukas.",
      "Hatiin sa maliliit na hakbang ang malalaking problema.",
      "Datos ang pagkabigo, hindi katapusan.",
      "Magsimula ngayon, hindi mamaya.",
      "Mas mahalaga ang isang oras na pokus kaysa buong araw na tamad.",
      "Nalagpasan mo na ang mas mahihirap na araw.",
      "Pagpapahalaga sa sarili ang disiplina.",
      "Huwag hayaang habulin ka ng deadline.",
      "Tapusin ang isa at damhin ang ginhawa.",
      "Hangarin lang ang plano kung walang aksyon.",
      "Okay ang mabagal, basta matapos.",
      "Sa iyo ang araw na ito. Gamitin nang husto.",
      "Tapos na ang proyekto, panatag ang isip.",
    ],
    'ru': [
      "Начните сейчас. Идеальное придёт потом.",
      "Маленький шаг сегодня лучше большого плана завтра.",
      "Сроки — друзья, а не враги.",
      "Не ждите мотивации. Воспитывайте дисциплину.",
      "Маленький прогресс — всё равно прогресс.",
      "Фокус. Работа. Результат.",
      "Сегодня решаете вы, а не лень.",
      "Устать можно. Сдаваться нельзя.",
      "Что откладываете сегодня, станет грузом завтра.",
      "Сделайте сейчас. Отдохнёте потом.",
      "Вы сильнее своих отговорок.",
      "Сделанное лучше идеального.",
      "Вычеркните сегодня хотя бы одно дело.",
      "Постоянство сильнее мотивации.",
      "Большие цели начинаются с маленьких задач.",
      "Не сравнивайте свой старт с чужим финишем.",
      "Время идёт. Идите вместе с ним.",
      "Поработайте сегодня — гордитесь завтра.",
      "Разбейте большую проблему на маленькие шаги.",
      "Неудача — это данные, а не конец.",
      "Начните сейчас, а не потом.",
      "Час концентрации лучше целого дня лени.",
      "Вы уже пережили дни и потруднее.",
      "Дисциплина — это уважение к себе.",
      "Не позволяйте сроку гнаться за вами.",
      "Закончите одно дело и почувствуйте облегчение.",
      "План без действий — просто мечта.",
      "Медленно — нормально, главное — довести до конца.",
      "Этот день ваш. Используйте его с умом.",
      "Проект готов, на душе спокойно.",
    ],
    'it': [
      "Inizia ora. Il perfetto arriverà dopo.",
      "Un piccolo passo oggi vale più di un grande piano domani.",
      "Le scadenze sono amiche, non nemiche.",
      "Non aspettare la motivazione. Costruisci disciplina.",
      "Un piccolo progresso è pur sempre un progresso.",
      "Concentrati. Lavora. Finisci.",
      "Oggi decidi tu, non la pigrizia.",
      "Essere stanchi va bene. Mollare no.",
      "Ciò che rimandi oggi diventa un peso domani.",
      "Fallo ora. Rilassati dopo.",
      "Sei più forte delle tue scuse.",
      "Fatto è meglio che perfetto.",
      "Spunta almeno una cosa oggi.",
      "La costanza batte la motivazione.",
      "I grandi obiettivi iniziano da piccoli compiti.",
      "Non paragonare il tuo inizio al traguardo degli altri.",
      "Il tempo non si ferma. Muoviti con lui.",
      "Impegnati oggi, sii orgoglioso domani.",
      "Spezza i grandi problemi in piccoli passi.",
      "Fallire è un dato, non la fine.",
      "Comincia adesso, non dopo.",
      "Un’ora di concentrazione vale più di una giornata pigra.",
      "Hai già superato giorni più duri.",
      "La disciplina è rispetto per se stessi.",
      "Non lasciare che la scadenza ti rincorra.",
      "Finisci una cosa e senti il sollievo.",
      "Un piano senza azione è solo un desiderio.",
      "Piano va bene, purché finisca.",
      "Oggi è tuo. Usalo bene.",
      "Progetto finito, mente serena.",
    ],
    'tr': [
      "Şimdi başla. Mükemmel olan sonra gelir.",
      "Bugünkü küçük bir adım, yarınki büyük bir plandan iyidir.",
      "Son tarihler düşman değil, dosttur.",
      "Motivasyonu bekleme. Disiplin kur.",
      "Küçük ilerleme de ilerlemedir.",
      "Odaklan. Çalış. Bitir.",
      "Bugün sen karar verirsin, tembellik değil.",
      "Yorulmak olur. Pes etmek olmaz.",
      "Bugün ertelediğin şey yarın yük olur.",
      "Şimdi yap. Sonra dinlen.",
      "Bahanelerinden daha güçlüsün.",
      "Bitmiş iş, mükemmel olandan iyidir.",
      "Bugün bir işi listeden çiz.",
      "İstikrar motivasyonu yener.",
      "Büyük hedefler küçük görevlerle başlar.",
      "Senin başlangıcını başkasının bitişiyle kıyaslama.",
      "Zaman akıyor. Sen de onunla ilerle.",
      "Bugün çalış, yarın gurur duy.",
      "Büyük sorunları küçük adımlara böl.",
      "Başarısızlık veridir, son değil.",
      "Şimdi başla, sonra değil.",
      "Odaklanılmış bir saat, tembel bir günden değerlidir.",
      "Bundan daha zor günleri atlattın.",
      "Disiplin, kendine saygıdır.",
      "Son tarihin seni kovalamasına izin verme.",
      "Bir işi bitir ve rahatlamayı hisset.",
      "Eylemsiz plan sadece bir dilektir.",
      "Yavaş olsun, yeter ki bitsin.",
      "Bugün senin. İyi değerlendir.",
      "Proje tamam, gönül rahat.",
    ],
  };

  static final Random _rng = Random();

  /// Resolves "zh-Hans" -> "zh", "pt-BR" -> "pt"; unknown languages fall back to English.
  static List<String> forLanguage(String? code) {
    final base = code?.split('-').first;
    return byLanguage[code] ?? byLanguage[base] ?? byLanguage['en']!;
  }

  static String random([String? languageCode]) {
    final list = forLanguage(languageCode);
    return list[_rng.nextInt(list.length)];
  }
}
